config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
  get '/help', 						to: 'pages#help'
  get '/contact', 				to: 'pages#contact'
	get '/privacy_policy', 	to: 'pages#privacy_policy'
	get '/register',				to: 'users#new'
	
	resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	VALID_NAME_REGEX = /\A[a-zA-Z-]+\z/i
	validates :user_forename, presence: true, length: {maximum: 35}, format: {with: VALID_NAME_REGEX}
	validates :user_surname, presence: true, length: {maximum: 35}, format: {with: VALID_NAME_REGEX}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :user_email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}
	validates :username, presence: true, length: {maximum: 35}	
	validates :api_sk, presence: true, length: {maximum: 50}	
	validates :api_pk, presence: true, length: {maximum: 50}	
	
	
	has_secure_password
	validates :password, presence: true, length: { minimum: 8 }
	
# validates_format_of :user_forename, :with => /\A[a-z]+\z/i
#	validates_format_of :user_surname, :with => /\A[a-z]+\z/i	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
	
	def privacy_policy
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def new
		@user = User.new
  end
	
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# If title isn't customised (eg. about/contact etc), display generic title
	def full_title (page_title = '')
		base_title = "VMS Secure Payments"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end		
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    <%= link_to "VMS Secure Payments.", '#' %>
    Powered by <a href="https://www.stripe.com/">Stripe</a>
  </small>
  <nav>
    <ul class="navbar-right">
			<small>
				<li><%= link_to "Help",   help_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><%= link_to "Privacy Policy", privacy_policy_path %></li>
			</small>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
		<div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>		
			<%= link_to image_tag("title_small.png", alt: "VMS logo"), root_path, id: "logo" %>
		</div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul id="nav-links" class="nav navbar-nav navbar-right header-align-bottom">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title><!-- Compose page title -->
		<%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  </head>

  <body>
		<%= render 'layouts/header' %>
		<div id="page-container" class="container-fluid">
    	<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">
	<h1>Pages#contact</h1>
	<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<div class="container">
	<h1>Pages#about</h1>
	<p>Find me in app/views/pages/about.html.erb</p>
</div>

app/views/pages/home.html.erb
<div class="parallax">
	<div class="center jumbotron">
		<h1>Welcome to VMS Secure Payments</h1>
		<h2>
			Request and Receive Payments Securely
		</h2>
		<%= link_to "Create Account", register_path, class: "btn btn-lg btn-primary" %>
	</div>
</div>

app/views/pages/privacy_policy.html.erb
<% provide(:title, "Privacy Policy") %>


<div id="privacy-policy" class="container">
  <h1>Privacy policy</h1>
  <p>We collect certain information or data about you when you use VMS Secure Payments.</p>
  <p>This includes:</p>
  <ul>
    <li>contact details (including your email address) for future correspondence</li>
    <li>information on how you use the site, using client storage to help us improve the website and personalise your experience</li>
  </ul>
  <p>This helps us to:</p>
  <ul>
    <li>improve the site by monitoring how you use it</li>
    <li>respond to any communication from you</li>
  </ul>


  <h2>Where your data is stored</h2>
  <p>We store your data on our secure servers.</p>

  <p>We do not store sensitive credit/debit card details.</p>
  


  <p>By submitting your personal data, you agree to this.</p>

  <h2>Keeping your data secure</h2>
  <p>Transmitting information over the internet is generally not completely secure, and we can’t guarantee the security of your data.</p>

	<p class="pp-bold">Any data you transmit is at your own risk.</p>

  <p>We have procedures and security features in place to try and keep your data secure once we receive it.</p>
  
  <p>Card details that we collect are processed by <a href="https://stripe.com/gb/payments">Stripe</a>. This helps to ensure that we are PCI-DSS compliant and your details are used safely.</p>

  <p class="pp-bold">Payment transactions are always encrypted.</p>
  
  <p>We won’t share your information with any other organisations for marketing, market research or commercial purposes, and we don’t pass on your details to other websites.</p>

  <h2>Disclosing your information</h2>
  <p>We may pass on your personal information if we have a legal obligation to do so.</p>

  <h2>Your rights</h2>
  <p>You can find out what information we hold about you <%= link_to "here", contact_path %>. You may also ask us not to use any of the information we collect.</p>

  <h2>Links to other websites</h2>
  <p>VMS Secure Payments contains links to and from other websites.</p>

  <p>This privacy policy only applies to this website.</p>

  <p class="pp-bold">Following a link to another website</p>

  <p>If you go to another website from this one, read the privacy policy on that website to find out what it does with your information.</p>

  <p class="pp-bold">Following a link to VMS Secure Payments from another website</p>

  <p>If you come to VMS Secure Payments from another website, we may receive personal information about you from the other website. You should read the privacy policy of the website you came from to find out more about this.</p>

  <p style="color: #708090">Last updated: 07 June 2017</p>
  <p style="color: #708090">This privacy policy has been adapted from <a href="https://www.gov.uk/help/privacy-policy">www.gov.uk/help/privacy-policy</a></p>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<div class="container">
	<h1>Register</h1>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= form_for(@user) do |f| %>
				<%= f.label 'Forename' %>
				<%= f.text_field :user_forename %>
			
				<%= f.label 'Surname' %>
				<%= f.text_field :user_surname %>			

				<%= f.label 'Email' %>
				<%= f.email_field :user_email %>
			
				<%= f.label :company %>
				<%= f.text_field :company %>
			
				<%= f.label :username %>
				<%= f.text_field :username %>		

				<%= f.label 'Logo URL' %>
				<%= f.email_field :logo_url %>
			
				<%= f.label 'Secret API Key' %>
				<%= f.text_field :api_sk %>
			
				<%= f.label 'Public API Key' %>
				<%= f.text_field :api_pk %>					

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>

				<%= f.submit "Create my account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>	
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<%= image_tag(@user.logo_url, alt: @user.username) %>